implement multiplanarShowRender
niivue/niivue pull request #1029
Opened 2024-07-11 16:06 UTC by hanayik

This PR implements the new option `multiplanarShowRender`. 

The main motivation for this new option is that the existing option, `multiplanarForceRender`, did not allow full control over the render tile slot when niivue is in multiplanar layout mode. 

I have implemented this in a way that preserves backwards compatibility with `multiplanarForceRender`. 

The logic is:
1. check if the user set `multiplanarForceRender=true`. 
2. if `multiplanarForceRender === true` then assume the user/developer has no knowledge of the new option `multiplanarShowRender`. NiiVue behaviour is identical to before. 
3. if `multiplanarForceRender === false` (the default value) then we inspect the value of `multiplanarShowRender`. 
4. if `multiplanarShowRender === 'always'` then we draw the render tile in multiplanar mode
5. if `multiplanarShowRender === 'never'` then we leave the render tile blank
6. if `multiplanarShowRender === 'auto'` (the default value) then we only draw the render tile if the NiiVue canvas aspect ratio allows us that space for free (this is how NiiVue worked prior to this change as well). 

So, basically, if someone sets `multiplanarForceRender=true` then we operate as if the new option does not exist. There is no behaviour change in NiiVue. 

If `multiplanarForceRender=false` and `multiplanarShowRender` is anything other than `auto` then we obey the user's wishes and do whatever `multiplanarShowRender` suggests.  

This backwards compatible implementation does not require any demo html updates since those will still work as before. 

List of fixed issues (if they exist):

- closes #1024

2024-07-11 16:24 UTC, neurolabusc commented
@hanayik in general this looks fine. However, I would change the behavior for when the old binary `multiplanarForceRender` is used, so that it converts this to the new ternary value and discards the obsolete option. This will purge the old property if the user saves the scene as a document. Indeed, while I leave it in the sample before, I would even remove the log.warn() as the new property is a superset of the old property, so old scenes will just work. 

```
if (this.opts.multiplanarForceRender) {
    log.warn('multiplanarForceRender is deprecated. Use multiplanarShowRender instead. Possible values are: "always", "auto", "never".')
    if (this.opts.multiplanarForceRender) {
        this.opts.multiplanarShowRender = 'always'
    } else {
        this.opts.multiplanarShowRender = 'auto'
    }
    delete this.opts.multiplanarForceRender;
}
```

2024-07-11 17:20 UTC, cdrake requested changes

2024-07-11 17:20 UTC, cdrake commented on src/niivue/index.ts
> +          if (this.opts.multiplanarShowRender === 'always') {
We should define an enum for this.

2024-07-11 17:20 UTC, cdrake commented on src/niivue/index.ts
> +            showRender = true
This should be renamed with "is", like isShowingRender to clarify that this is a boolean.

2024-07-12 09:58 UTC, hanayik commented
@neurolabusc and @cdrake, I have implemented your suggestions and tested. Once the tests pass in github I will merge this and release a new version so the feature is published. I am eager to use this new option in one of my projects.

2024-07-13 17:40 UTC, neurolabusc commented
@hanayik I committed a PR directly into your refactor branch that updates the live demos to use the modern usage. It also addresses a regression with legends that are wider than the canvas.

I updated the live demo recipes to remove deprecated property. The end to end tests still include the deprecated property. Most of these should probably be updated as well (though perhaps you want to keep one to ensure that we still support deprecated usage).

With these changes, I approve your PR and I encourage you to merge this PR if my changes meet your standards.

2024-07-15 20:36 UTC, merged